fix(PM-11): update yaml + dockerfile

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -13,11 +13,8 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Login to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Log in to Docker Hub
+      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u vonodev --password-stdin
 
     - name: Build and Push Docker image
       run: |
@@ -29,15 +26,35 @@ jobs:
       with:
         ssh-private-key: ${{ secrets.BE_AWS_KEY }}
 
+    - name: Clean up old Docker containers and images on EC2
+      run: |
+          ssh -o StrictHostKeyChecking=no ubuntu@52.221.208.107 << 'EOF'          
+            set -e
+            echo "Pulling latest image..."
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/be-nest-app:${TAG}
+            
+            echo "Stopping and removing old container (if any)..."
+            # Remove old containers if they exist
+            sudo docker stop be-nest-app || true
+            sudo docker rm be-nest-app || true
+            
+            echo "Running new container..."
+            # Clean up unused images and dangling containers to free space
+            sudo docker image prune -a -f
+            sudo docker container prune -f
+            sudo docker volume prune -f
+          EOF
+
     - name: Deploy on EC2
       run: |
         ssh -o StrictHostKeyChecking=no ubuntu@52.221.208.107 << 'EOF'
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/be-nest-app:latest
+          set -e
+          sudo docker pull vonodev/be-nest-app:latest
           sudo docker stop be-nest-app || true
           sudo docker rm be-nest-app || true
           sudo docker run -d \
             --name be-nest-app \
             --env-file /home/ubuntu/be-journey/.env.production \
             -p 3000:3000 \
-            ${{ secrets.DOCKER_USERNAME }}/be-nest-app:latest
+            vonodev/be-nest-app:latest
         EOF
