feat(PM-29): bullQueue upload files

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,56 +1,56 @@
-name: Deploy NestJS to EC2 using Docker Hub
+# name: Deploy NestJS to EC2 using Docker Hub
 
-on:
-  push:
-    branches:
-      - master
+# on:
+#   push:
+#     branches:
+#       - master
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
 
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
 
-    - name: Log in to Docker Hub
-      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u vonodev --password-stdin
+#     - name: Log in to Docker Hub
+#       run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u vonodev --password-stdin
 
-    - name: Build and Push Docker image
-      run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/be-nest-app:latest .
-        docker push ${{ secrets.DOCKER_USERNAME }}/be-nest-app:latest
+#     - name: Build and Push Docker image
+#       run: |
+#         docker build -t ${{ secrets.DOCKER_USERNAME }}/be-nest-app:latest .
+#         docker push ${{ secrets.DOCKER_USERNAME }}/be-nest-app:latest
 
-    - name: Setup SSH Agent
-      uses: webfactory/ssh-agent@v0.7.0
-      with:
-        ssh-private-key: ${{ secrets.BE_AWS_KEY }}
+#     - name: Setup SSH Agent
+#       uses: webfactory/ssh-agent@v0.7.0
+#       with:
+#         ssh-private-key: ${{ secrets.BE_AWS_KEY }}
 
-    - name: Clean up old Docker containers and images on EC2
-      run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@52.221.208.107 << 'EOF'          
-            set -e
-            # Remove old containers if they exist
-            sudo docker stop be-nest-app || true
-            sudo docker rm be-nest-app || true
+#     - name: Clean up old Docker containers and images on EC2
+#       run: |
+#           ssh -o StrictHostKeyChecking=no ubuntu@52.221.208.107 << 'EOF'          
+#             set -e
+#             # Remove old containers if they exist
+#             sudo docker stop be-nest-app || true
+#             sudo docker rm be-nest-app || true
             
-            echo "Running new container..."
-            # Clean up unused images and dangling containers to free space
-            sudo docker image prune -a -f
-            sudo docker container prune -f
-            sudo docker volume prune -f
-          EOF
+#             echo "Running new container..."
+#             # Clean up unused images and dangling containers to free space
+#             sudo docker image prune -a -f
+#             sudo docker container prune -f
+#             sudo docker volume prune -f
+#           EOF
 
-    - name: Deploy on EC2
-      run: |
-        ssh -o StrictHostKeyChecking=no ubuntu@52.221.208.107 << 'EOF'
-          set -e
-          sudo docker pull vonodev/be-nest-app:latest
-          sudo docker stop be-nest-app || true
-          sudo docker rm be-nest-app || true
-          sudo docker run -d \
-            --name be-nest-app \
-            --env-file /home/ubuntu/be-journey/.env.production \
-            -p 3000:3000 \
-            vonodev/be-nest-app:latest
-        EOF
+#     - name: Deploy on EC2
+#       run: |
+#         ssh -o StrictHostKeyChecking=no ubuntu@52.221.208.107 << 'EOF'
+#           set -e
+#           sudo docker pull vonodev/be-nest-app:latest
+#           sudo docker stop be-nest-app || true
+#           sudo docker rm be-nest-app || true
+#           sudo docker run -d \
+#             --name be-nest-app \
+#             --env-file /home/ubuntu/be-journey/.env.production \
+#             -p 3000:3000 \
+#             vonodev/be-nest-app:latest
+#         EOF
